version: '3.8'
services:
   # Replica Set (required for Prisma Client)
  barbershop:
    build: ./mongodb_replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: barbershop
      MONGO_INITDB_ROOT_PASSWORD: barbershop
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27018
    ports:
      - '27018:27018'
volumes:
  mongo-db: